# Generated by Django 2.2.28 on 2024-03-16 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('continent', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('South America', 'South America'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania')], max_length=10)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('vibe', models.CharField(choices=[('Party', 'Party'), ('Adventure', 'Adventure'), ('Romantic', 'Romantic'), ('Relaxed', 'Relaxed')], default='', max_length=128)),
                ('setting', models.CharField(choices=[('City', 'City'), ('Beach', 'Beach'), ('Mountains', 'Mountains'), ('Countryside', 'Countryside')], default='', max_length=128)),
                ('travelPartners', models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Partner', 'Partner'), ('Solo', 'Solo')], default='', max_length=128)),
                ('climate', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Mixed', 'Mixed')], default='', max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triptales.Country')),
            ],
        ),
        migrations.CreateModel(
            name='VacationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x74674bc3ecd0>, <django.db.models.query_utils.DeferredAttribute object at 0x74674bc37760>', max_length=128)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triptales.Country')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triptales.Location')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('bio', models.TextField(blank=True)),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_by_users', to='triptales.VacationPost')),
                ('posts_made', models.ManyToManyField(blank=True, related_name='posts_made', to='triptales.VacationPost')),
                ('saved_posts', models.ManyToManyField(blank=True, related_name='saved_by_users', to='triptales.VacationPost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triptales.VacationPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
