# Generated by Django 2.2.28 on 2024-03-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('continent', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('South America', 'South America'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania')], max_length=10)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts_made',
            field=models.ManyToManyField(blank=True, related_name='posts_made', to='triptales.VacationPost'),
        ),
        migrations.AddField(
            model_name='vacationpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('vibe', models.CharField(choices=[('Party', 'Party'), ('Adventure', 'Adventure'), ('Romantic', 'Romantic'), ('Relaxed', 'Relaxed')], default='', max_length=128)),
                ('setting', models.CharField(choices=[('City', 'City'), ('Beach', 'Beach'), ('Mountains', 'Mountains'), ('Countryside', 'Countryside')], default='', max_length=128)),
                ('travelPartners', models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Partner', 'Partner'), ('Solo', 'Solo')], default='', max_length=128)),
                ('climate', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Mixed', 'Mixed')], default='', max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triptales.Country')),
            ],
        ),
        migrations.AddField(
            model_name='vacationpost',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triptales.Country'),
        ),
        migrations.AddField(
            model_name='vacationpost',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='triptales.Location'),
        ),
    ]
