# Generated by Django 2.2.28 on 2024-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x78b3d5906cd0>, <django.db.models.query_utils.DeferredAttribute object at 0x78b3d5900760>', max_length=128),
        ),
    ]
