# Generated by Django 2.2.28 on 2024-03-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
