# Generated by Django 3.2.13 on 2024-03-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x0000025A84AEEC40>, <django.db.models.query_utils.DeferredAttribute object at 0x0000025A84AE18E0>', max_length=128),
        ),
    ]
