# Generated by Django 2.2.28 on 2024-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0002_auto_20240322_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x7503602cad60>, <django.db.models.query_utils.DeferredAttribute object at 0x7503602c47c0>', max_length=128),
        ),
    ]
