# Generated by Django 2.2.28 on 2024-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0002_auto_20240316_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x743d328aad30>, <django.db.models.query_utils.DeferredAttribute object at 0x743d328a37c0>', max_length=128),
        ),
    ]