# Generated by Django 2.1.5 on 2024-03-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0003_auto_20240322_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x000001E1F8009550>, <django.db.models.query_utils.DeferredAttribute object at 0x000001E1F80139A0>', max_length=128),
        ),
    ]
