# Generated by Django 3.2.13 on 2024-03-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0004_alter_vacationpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x000001229938EC40>, <django.db.models.query_utils.DeferredAttribute object at 0x00000122993818E0>', max_length=128),
        ),
    ]
