# Generated by Django 2.2.28 on 2024-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0005_auto_20240319_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x0000020F10CE7730>, <django.db.models.query_utils.DeferredAttribute object at 0x0000020F10CDEE50>', max_length=128),
        ),
    ]
