# Generated by Django 2.2.28 on 2024-03-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0009_auto_20240321_2015'),
        ('triptales', '0006_auto_20240320_0345'),
    ]

    operations = [
    ]
