# Generated by Django 2.2.28 on 2024-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptales', '0010_merge_20240321_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationpost',
            name='title',
            field=models.CharField(default='Trip to <django.db.models.query_utils.DeferredAttribute object at 0x0000016DD84F7730>, <django.db.models.query_utils.DeferredAttribute object at 0x0000016DD84EEE80>', max_length=128),
        ),
    ]
